### ISSUE TITLE
WebRtc-H264Capturer docker

### ISSUE THREAD

**Issue by Classsic** [nicotyze/Webrtc-H264Capturer#7]
Hi, somebody build this in a docker? I try but get many errors on build. Any suggestion, welcome.

**Comment by nicotyze** [comment]
Hi,
I've just pushed a new commit which is an update to M55 release. For
unknown reasons, the git checkout to the previous flag does not work
anymore (and produce many errors)...
I've never tested with docker but maybe your errors are due to the broken
checkout.



2017-10-12 5:07 GMT+02:00 Classsic <notifications@github.com>:

**Comment by Classsic** [comment]
When run  ` gn gen out/Default --args='is_component_ffmpeg=true'` I get this error:
ERROR at //build/config/linux/pkg_config.gni:85:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /root/webrtc-checkout/src/out/Default/
Command: python -- /root/webrtc-checkout/src/build/config/linux/pkg-config.py -s /root/webrtc-checkout/src/build/linux/debian_wheezy_amd64-sysroot -a x64 gmodule-2.0 gtk+-2.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/root/webrtc-checkout/src/build/config/linux/pkg-config.py", line 219, in <module>
    sys.exit(main())
  File "/root/webrtc-checkout/src/build/config/linux/pkg-config.py", line 138, in main
    prefix = GetPkgConfigPrefixToStrip(args)
  File "/root/webrtc-checkout/src/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //webrtc/examples/BUILD.gn:361:5: whence it was called.
    pkg_config("gtk2_config") {
    ^--------------------------
See //BUILD.gn:13:5: which caused the file to be included.
    "//webrtc/examples",
    ^------------------
Can you pointme please.
Thanks.

**Comment by nicotyze** [comment]
I suspect that your last  glcient sync did not finish properly.
Does the src/build/linux/debian_wheezy_amd64-sysroot directory exist ?

If the answer is no, I would suggest you to redo the entire process in a
fresh directory...

First get Webrtc source code (as it is described in the Readme):

> mkdir webrtc-checkout
> cd webrtc-checkout
> fetch --nohooks webrtc
> gclient sync --with_branch_heads
> export WEBRTC_DIR=`pwd`

and then (slightly different from the readme: after the checkout to M55
release, the next gclient sync should stop asking you to run the python
setup_links script manually => run the the script and accept the proposed
modifications and finally run a last gclient sync):

> cd $WEBRTC_DIR/src
> git checkout branch-heads/55
> gclient sync
> python setup_links.py --force
> gclient sync




2017-10-20 3:32 GMT+02:00 Classsic <notifications@github.com>:
